# Generated by Django 4.2.16 on 2024-11-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_certifications_experience_remove_skill_proficient_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Work_Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=50)),
                ("company_name", models.CharField(max_length=50)),
                ("work_duration", models.CharField(max_length=50)),
                ("desc", models.TextField()),
                ("technologies", models.TextField()),
            ],
        ),
    ]
